module.exports = {
  apps: [
    {
      name: 'multisig-backend',
      cwd: './backend',
      script: './target/release/multisigmonitor-backend',
      interpreter: 'none',
      env_file: '../secrets/.env.backend.prod',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      error_file: './logs/backend-error.log',
      out_file: './logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'multisig-worker',
      cwd: './backend',
      script: './target/release/monitor-worker',
      interpreter: 'none',
      env_file: '../secrets/.env.backend.prod',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      error_file: './logs/worker-error.log',
      out_file: './logs/worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
