// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgqotbhokyuasepuhzxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpncW90Ymhva3l1YXNlcHVoenh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NDMzMTksImV4cCI6MjA1OTExOTMxOX0.dRnlnp8uD8DmXNZzA0VWg0iQSjKk_4OxNzuoas9zCIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);